@extends("layouts._admin")
@section("title", "Edit Client")
@section("css")
    <style>


    </style>
@endsection

@section("content")
    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>@yield("title")</h1>
                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h2>Basic Information</h2>
                    </div>
                    <div class="body">
                        <form method="POST" enctype="multipart/form-data" id="basic-form" novalidate
                              action="{{ route('admin.client.update', $client->id) }}">
                            @csrf
                            <input type="hidden" name="id" value="{{$client->id}}">
                            <div class="row clearfix">
                                <div class="col-sm-12 ">
                                    <div class="form-group">
                                        <label for="autogenerated" class="control-label">Code No.</label>
                                        <input value="{{$client->id}}" type="text" readonly disabled
                                               class="form-control"
                                               id="autogenerated" name="autogenerated">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="fname" class="control-label">First Name <span class="required">*</span></label>
                                        <input value="{{ $client->fname }}" type="text"
                                               class="form-control @if ($errors->has('fname'))is-invalid @endif"
                                               id="fname" name="fname" required>


                                        @if ($errors->has('fname'))
                                            <p class="text-danger">{{$errors->first('fname')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="lname" class="control-label">Last Name <span class="required">*</span></label>
                                        <input value="{{ $client->lname }}" type="text"
                                               class="form-control @if ($errors->has('lname'))is-invalid @endif" id="lname"
                                               name="lname" required>
                                        @if ($errors->has('lname'))
                                            <p class="text-danger">{{$errors->first('lname')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="phone" class="control-label">Phone No. <span class="required">*</span></label>
                                        <input value="{{$client->phone }}" type="tel"
                                               class="form-control @if ($errors->has('phone'))is-invalid @endif" id="phone"
                                               name="phone" required>

                                        @if ($errors->has('phone'))
                                            <p class="text-danger">{{$errors->first('phone')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="email" class="control-label">E-mail Address <span class="required">*</span></label>
                                        <input value="{{$client->email }}" type="email"
                                               class="form-control  @if ($errors->has('email'))is-invalid @endif" id="email"
                                               name="email" required>

                                        @if ($errors->has('email'))
                                            <p class="text-danger">{{$errors->first('email')}}</p>
                                        @endif
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="position" class="control-label">Position <span class="required">*</span></label>
                                        <input value="{{ $client->position }}" type="text"
                                               class="form-control @if ($errors->has('position'))is-invalid @endif"
                                               id="position" name="position">

                                        @if ($errors->has('position'))
                                            <p class="text-danger">{{$errors->first('position')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="position" class="control-label">Address <span class="required">*</span></label>
                                        <input value="{{ $client->address }}" type="text"
                                               class="form-control @if ($errors->has('address'))is-invalid @endif"
                                               id="address" name="address">

                                        @if ($errors->has('address'))
                                            <p class="text-danger">{{$errors->first('address')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="company_name" class="control-label">Company Name <span class="required">*</span></label>
                                        <input value="{{ $client->clientinfo->companyName }}" type="text"
                                               class="form-control @if ($errors->has('companyName'))is-invalid @endif"
                                               id="companyName" name="companyName" required>

                                        @if ($errors->has('companyName'))
                                            <p class="text-danger">{{$errors->first('companyName')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="company_field" class="control-label">Company Field <span class="required">*</span></label>
                                        <input value="{{ $client->clientinfo->companyField }}" type="text"
                                               class="form-control @if ($errors->has('companyField'))is-invalid @endif"
                                               id="companyField" name="companyField" required>

                                        @if ($errors->has('companyField'))
                                            <p class="text-danger">{{$errors->first('companyField')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="company_number" class="control-label">Company No. <span class="required">*</span></label>
                                        <input value="{{ $client->clientinfo->companyNo }}" type="text"
                                               class="form-control @if ($errors->has('companyNo'))is-invalid @endif"
                                               id="companyNo" name="companyNo" required>

                                        @if ($errors->has('companyNo'))
                                            <p class="text-danger">{{$errors->first('companyNo')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="password" class="control-label">Password</label>
                                        <input value="" type="password"
                                               class="form-control @if ($errors->has('password'))is-invalid @endif"
                                               id="password" name="password">

                                        @if ($errors->has('password'))
                                            <p class="text-danger">{{$errors->first('password')}}</p>
                                        @endif
                                    </div>
                                </div>

                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                    <a class="btn btn-dark" href="{{ route('admin.client.index') }}">Back</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

