{{-- edit form >>  manager   --}}

@extends("layouts._admin")
@section("title", "Edit  Manager")
@section("css")
    <style>

    </style>
@endsection

@section("content")

    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>@yield("title")</h1>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h2>Basic Information</h2>
                    </div>
                    <div class="body">

                        <form class="ml-3" method="POST" action="{{ route('admin.manger.update', $user->id) }}"
                              enctype="multipart/form-data">
                            @csrf
                            <input type="hidden" value="{{$user->id}}" name="id">
                            <div class="row clearfix">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="autogenerated" class="control-label">Code No.</label>
                                        <input value="{{$user->id_number}}" type="text" readonly disabled
                                               class="form-control @if ($errors->has('fname'))is-invalid @endif"
                                               id="autogenerated" name="autogenerated">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="fname" class="control-label">First Name <span class="required">*</span></label>
                                        <input value="{{$user->fname}}" type="text"
                                               class="form-control @if ($errors->has('fname'))is-invalid @endif"
                                               id="fname" name="fname">
                                        @if ($errors->has('fname'))
                                            <p class="text-danger">{{$errors->first('fname')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="lname" class="control-label">Last Name <span class="required">*</span></label>
                                        <input value="{{$user->lname}}" type="text"
                                               class="form-control @if ($errors->has('lname'))is-invalid @endif" id="lname"
                                               name="lname">

                                        @if ($errors->has('lname'))
                                            <p class="text-danger">{{$errors->first('lname')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="phone" class="control-label">Phone No. <span class="required">*</span></label>
                                        <input value="{{$user->phone }}" type="tel"
                                               class="form-control @if ($errors->has('phone'))is-invalid @endif"
                                               id="phone" name="phone">
                                        @if ($errors->has('phone'))
                                            <p class="text-danger">{{$errors->first('phone')}}</p>
                                        @endif

                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="identity" class="control-label">Emirates Id / Passport No. <span class="required">*</span></label>
                                        <input value="{{$user->identity }}" type="text"
                                               class="form-control @if ($errors->has('identity')) is-invalid @endif"
                                               id="identity" name="identity">
                                        @if ($errors->has('identity'))
                                            <p class="text-danger">{{$errors->first('identity')}}</p>
                                        @endif

                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="email" class="control-label">E-mail Address <span class="required">*</span></label>
                                        <input value="{{$user->email }}" type="email"
                                               class="form-control @if ($errors->has('email'))is-invalid @endif" id="email"
                                               name="email">
                                        @if ($errors->has('email'))
                                            <p class="text-danger">{{$errors->first('email')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="position" class="control-label">Position <span class="required">*</span></label>
                                        <input value="{{ $user->position }}" type="text"
                                               class="form-control @if ($errors->has('position'))is-invalid @endif"
                                               id="position" name="position">

                                        @if ($errors->has('position'))
                                            <p class="text-danger">{{$errors->first('position')}}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="password" class="control-label">Password <span class="required">*</span></label>
                                        <input value="" type="password"
                                               class="form-control @if ($errors->has('password'))is-invalid @endif"
                                               id="password" name="password">

                                        @if ($errors->has('password'))
                                            <p class="text-danger">{{$errors->first('password')}}</p>
                                        @endif
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-12">
                                    <div class="form-group">
                                        <label for="address" class="control-label">Address <span class="required">*</span></label>
                                        <input value="{{ $user->address }}" type="text"
                                               class="form-control @if ($errors->has('address'))is-invalid @endif"
                                               id="address" name="address">

                                        @if ($errors->has('address'))
                                            <p class="text-danger">{{$errors->first('address')}}</p>
                                        @endif
                                    </div>
                                </div>

                            </div>
                            <br>


                            <div class="col-xs-12">
                                <button type="submit" class="btn btn-primary">Update</button>
                                <a class="btn btn-dark" href="{{ route('admin.manger.index') }}">Back</a>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>

    </div>


    </div>
@endsection






{{--@extends("layouts._admin")--}}

{{--@section("title", "Edit Managers")--}}

{{--@section("css")--}}
{{--  <style>--}}

{{--  </style>--}}
{{--@endsection--}}

{{--@section("content")--}}
{{--<form class="w-50" method="POST" enctype="multipart/form-data"  action="{{ route('admin.manger.update', $user->id) }}">--}}
{{--@csrf--}}
{{--  <div class="form-group">--}}
{{--    <label for="name"> First Name </label>--}}
{{--    <input autofocus value="{{ $user->fname }}" type="text" class="form-control" id="fname" name="fname">--}}

{{--</div>--}}
{{--<div class="form-group">--}}
{{--    <label for="name"> Last Name </label>--}}
{{--    <input autofocus value="{{ $user->lname }}" type="text" class="form-control" id="lname" name="lname" >--}}

{{--</div>--}}
{{--<div class="form-group">--}}
{{--    <label for="name"> Phone </label>--}}
{{--    <input autofocus value="{{ $user->phone }}" type="text" class="form-control" id="phone" name="phone" >--}}

{{--</div>--}}
{{--<div class="form-group">--}}
{{--    <label for="name"> Email </label>--}}
{{--    <input autofocus value="{{ $user->email }}" type="text" class="form-control" id="email" name="email" >--}}

{{--</div>--}}


{{--<div class="form-group">--}}
{{--    <label for="name"> Address </label>--}}
{{--    <input autofocus value="{{ $user->address }}" type="text" class="form-control" id="address" name="address" >--}}

{{--</div>--}}
{{--<div class="form-group">--}}
{{--        <label for="fle_photo"> Photo:</label>--}}
{{--        <input type="file" class="form-control" id="fle_photo" name="fle_photo" placeholder="photo  ">--}}
{{--        @if($user->photo)--}}
{{--            <img src='{{ asset("assest/upload/" . $user->photo) }}' class="mt-2 w-50 img-fluid img-thumbnail" />--}}
{{--        @endif--}}
{{--    </div>--}}

{{--  <button type="submit" class="btn btn-primary">Update</button>--}}

{{--  <a class="btn btn-dark" href="{{ route('admin.manger.index') }}">Back</a>--}}
{{--</form>--}}

{{--@endsection--}}

